### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by Burgess12138** [yohan-pg/robust-unsupervised#2]
I have not seen the pre-trained model and corresponding test code you provided in your project, may I ask whether these will be released later? What is the approximate time？

**Comment by yohan-pg** [comment]
Hi, this repo uses the pretrained StyleGAN2 model from https://github.com/NVlabs/stylegan2-ada-pytorch.
You can download ffhq.pkl from this URL: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/
